### ISSUE TITLE
Add parameters to Census utility

### ISSUE THREAD

**Issue by ncsa-mo** [IN-CORE/pyincore-data#21]
Hardwired Census API parameters are get_vars = 'GEO_ID,NAME,P005001,P005003,P005004,P005010' and for=block%20group:*.
For Galveston analysis we also need get=GEO_ID,NAME,B25002_001E,B25002_001M,B25004_006E,B25004_006M and for=tract:*. The best way is to create a class parameters for `get` and `for`.

**Comment by ywkim312** [comment]
This will work by using the following code

```
    acs5_year = "2020"
    acs5_data_source = 'acs/acs5'
    acs5_columns = 'GEO_ID,NAME,B25002_001E,B25002_001M,B25004_006E,B25004_006M'
    state='42'
    county='017,029,045,091,101'
    geo_type = 'tract:*'
    # geo_type = 'block%20group:*'

    api_json, api_df = CensusUtil.get_census_data(state, county, acs5_year, acs5_data_source, acs5_columns, geo_type)```
